var namespaces_dup =
[
    [ "bar", "namespacebar.html", null ],
    [ "foo", "namespacefoo.html", "namespacefoo" ],
    [ "gmock_leak_test", "namespacegmock__leak__test.html", "namespacegmock__leak__test" ],
    [ "gmock_output_test", "namespacegmock__output__test.html", "namespacegmock__output__test" ],
    [ "gmock_test_utils", "namespacegmock__test__utils.html", [
      [ "GetExitStatus", "namespacegmock__test__utils.html#a50a969d22467b37ee1a10bc2a9033b59", null ],
      [ "GetSourceDir", "namespacegmock__test__utils.html#a02a2cf54e2808e29aaba6712a368432f", null ],
      [ "GetTestExecutablePath", "namespacegmock__test__utils.html#a7cef788e502f48e04bccf07abfa3d246", null ],
      [ "Main", "namespacegmock__test__utils.html#a41b291984bc12db5e1056a056bc79ba1", null ],
      [ "environ", "namespacegmock__test__utils.html#a6f0938b5e8839ebc847b52a38f4d35e3", null ],
      [ "PREMATURE_EXIT_FILE_ENV_VAR", "namespacegmock__test__utils.html#a9392c288e6da3024d65ec0bddc0d86c3", null ],
      [ "SetEnvVar", "namespacegmock__test__utils.html#ab0c69f8ce649fdd5a17f99deedf3eb29", null ],
      [ "Subprocess", "namespacegmock__test__utils.html#a31a0e33565ec805d314cb0a4eb8317e6", null ],
      [ "TestCase", "namespacegmock__test__utils.html#a959c5af591e4d49b6d35745205b64509", null ]
    ] ],
    [ "googletest", "namespacegoogletest.html", null ],
    [ "googletest-break-on-failure-unittest", "namespacegoogletest-break-on-failure-unittest.html", "namespacegoogletest-break-on-failure-unittest" ],
    [ "googletest-catch-exceptions-test", "namespacegoogletest-catch-exceptions-test.html", "namespacegoogletest-catch-exceptions-test" ],
    [ "googletest-color-test", "namespacegoogletest-color-test.html", "namespacegoogletest-color-test" ],
    [ "googletest-env-var-test", "namespacegoogletest-env-var-test.html", "namespacegoogletest-env-var-test" ],
    [ "googletest-failfast-unittest", "namespacegoogletest-failfast-unittest.html", "namespacegoogletest-failfast-unittest" ],
    [ "googletest-filter-unittest", "namespacegoogletest-filter-unittest.html", "namespacegoogletest-filter-unittest" ],
    [ "googletest-global-environment-unittest", "namespacegoogletest-global-environment-unittest.html", "namespacegoogletest-global-environment-unittest" ],
    [ "googletest-json-outfiles-test", "namespacegoogletest-json-outfiles-test.html", "namespacegoogletest-json-outfiles-test" ],
    [ "googletest-json-output-unittest", "namespacegoogletest-json-output-unittest.html", "namespacegoogletest-json-output-unittest" ],
    [ "googletest-list-tests-unittest", "namespacegoogletest-list-tests-unittest.html", "namespacegoogletest-list-tests-unittest" ],
    [ "googletest-output-test", "namespacegoogletest-output-test.html", "namespacegoogletest-output-test" ],
    [ "googletest-param-test-invalid-name1-test", "namespacegoogletest-param-test-invalid-name1-test.html", "namespacegoogletest-param-test-invalid-name1-test" ],
    [ "googletest-param-test-invalid-name2-test", "namespacegoogletest-param-test-invalid-name2-test.html", "namespacegoogletest-param-test-invalid-name2-test" ],
    [ "googletest-setuptestsuite-test", "namespacegoogletest-setuptestsuite-test.html", "namespacegoogletest-setuptestsuite-test" ],
    [ "googletest-shuffle-test", "namespacegoogletest-shuffle-test.html", "namespacegoogletest-shuffle-test" ],
    [ "googletest-throw-on-failure-test", "namespacegoogletest-throw-on-failure-test.html", "namespacegoogletest-throw-on-failure-test" ],
    [ "googletest-uninitialized-test", "namespacegoogletest-uninitialized-test.html", "namespacegoogletest-uninitialized-test" ],
    [ "gtest_help_test", "namespacegtest__help__test.html", "namespacegtest__help__test" ],
    [ "gtest_json_test_utils", "namespacegtest__json__test__utils.html", [
      [ "normalize", "namespacegtest__json__test__utils.html#a80d4973d53f6cff720dc70f2db4cdc0b", null ]
    ] ],
    [ "gtest_list_output_unittest", "namespacegtest__list__output__unittest.html", "namespacegtest__list__output__unittest" ],
    [ "gtest_skip_check_output_test", "namespacegtest__skip__check__output__test.html", "namespacegtest__skip__check__output__test" ],
    [ "gtest_skip_environment_check_output_test", "namespacegtest__skip__environment__check__output__test.html", "namespacegtest__skip__environment__check__output__test" ],
    [ "gtest_test_utils", "namespacegtest__test__utils.html", "namespacegtest__test__utils" ],
    [ "gtest_testbridge_test", "namespacegtest__testbridge__test.html", "namespacegtest__testbridge__test" ],
    [ "gtest_xml_outfiles_test", "namespacegtest__xml__outfiles__test.html", "namespacegtest__xml__outfiles__test" ],
    [ "gtest_xml_output_unittest", "namespacegtest__xml__output__unittest.html", "namespacegtest__xml__output__unittest" ],
    [ "gtest_xml_test_utils", "namespacegtest__xml__test__utils.html", "namespacegtest__xml__test__utils" ],
    [ "library1", "namespacelibrary1.html", "namespacelibrary1" ],
    [ "library2", "namespacelibrary2.html", "namespacelibrary2" ],
    [ "my_namespace", "namespacemy__namespace.html", "namespacemy__namespace" ],
    [ "namespace1", "namespacenamespace1.html", "namespacenamespace1" ],
    [ "namespace2", "namespacenamespace2.html", "namespacenamespace2" ],
    [ "proto2", "namespaceproto2.html", null ],
    [ "std", "namespacestd.html", "namespacestd" ],
    [ "testing", "namespacetesting.html", "namespacetesting" ],
    [ "works_here", "namespaceworks__here.html", "namespaceworks__here" ]
];